package com.ex;

class StackOverflowException extends Exception
{
	public String toString()
	{
		return "Stack is Full";
	}
}

class StackUnderflow extends Exception
{
	
	public String toString()
	{
		return "Stack is Empty";
	}
}

class Stack
{
	private int size;
	private int top = -1;
	private int s[];
	
	public Stack(int sz)
	{
		size = sz;
		s = new int[sz];
	}
	
	public void push(int x) throws StackOverflow
	{
		if(top==size-1)
			throw new StackOverflow();
		top++;
		s[top] = x;
	}
	
	public int pop() throws StackUnderflow
	{
		int x = 1;
		
		if(top==-1)
			throw new StackUnderflow();
		x = s[top];
		top--;
		return x;
	}
}


public class EXceptionPractice {

	public static void main(String[] args) {
		
		Stack st = new Stack(5);
		try
		{
		st.push(10);
		st.push(15);
		st.push(10);
		st.push(15);
		st.push(10);
		st.push(15);
		}
		
		
		
		catch(StackOverflow s)
		{
			System.out.println(s);
		}
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
		}
	}

}
